CONFIG_MAX_XLAT_TABLES=16

# Core SPI
CONFIG_SPI=y
CONFIG_SPI_DW=y
CONFIG_SPI_DW_USE_IRQ=n
CONFIG_SPI_DW_POLLING_TIMEOUT_US=50000
CONFIG_SPI_LOG_LEVEL_ERR=y

# =========================
# Pin Controller
# =========================
CONFIG_PINCTRL=y
CONFIG_PINCTRL_RP1=y
# Logging for RP1 pinctrl
CONFIG_PINCTRL_RP1_LOG_LEVEL_DBG=y

# Ensure GPIO is enabled (required for bitbang)
CONFIG_GPIO=y

# Network stack
CONFIG_NET_ARP=y
CONFIG_NET_IPV4=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y

CONFIG_NET_IF_UNICAST_IPV4_ADDR_COUNT=2
CONFIG_NET_IF_MCAST_IPV4_ADDR_COUNT=1
CONFIG_NET_CONFIG_MY_IPV4_ADDR="10.1.1.5"
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"
CONFIG_NET_CONFIG_MY_IPV4_GW="0.0.0.0"
CONFIG_NET_CONFIG_INIT_TIMEOUT=5

CONFIG_NET_PKT_TX_COUNT=32
CONFIG_NET_PKT_RX_COUNT=32

CONFIG_NET_BUF_TX_COUNT=128
CONFIG_NET_BUF_RX_COUNT=128

CONFIG_NET_BUF_DATA_SIZE=256

CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=n
CONFIG_NET_UDP=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_ETHERNET_LOG_LEVEL_DBG=y

# TCP
CONFIG_NET_MAX_CONTEXTS=8
CONFIG_NET_MAX_CONN=8
CONFIG_ZVFS_POLL_MAX=4
CONFIG_ZVFS_OPEN_MAX=8

# LAN865x + MDIO
CONFIG_ETH_LAN865X=y
CONFIG_MDIO=y
CONFIG_MDIO_LAN865X=y
CONFIG_ETH_LAN865X_USE_IRQ=n
CONFIG_ETH_LAN865X_IRQ_THREAD_PRIO=10
CONFIG_ETH_LAN865X_IRQ_THREAD_STACK_SIZE=4096
CONFIG_ETH_LAN865X_POLL_INTERVAL_MS=1
CONFIG_ETH_LAN865X_BURST_CHUNKS=48

# === Console / UART ===
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# Shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_BACKEND_SERIAL_INIT_PRIORITY=50

# printk / log
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=4

CONFIG_PM=y
CONFIG_PM_DEVICE=y

CONFIG_PCIE=y
CONFIG_PCIE_CONTROLLER=y
CONFIG_PCIE_MSI=y
CONFIG_PCIE_MSI_X=y
CONFIG_DYNAMIC_INTERRUPTS=y
CONFIG_PCIE_MSI_MULTI_VECTOR=y
CONFIG_PCIE_LOG_LEVEL_DBG=y

CONFIG_I2C=n
CONFIG_I2C_DW=n
CONFIG_I2C_SHELL=n
CONFIG_I2C_LOG_LEVEL_DBG=n

CONFIG_GPIO_FXL6408=n

CONFIG_KERNEL_LOG_LEVEL_INF=y
CONFIG_KERNEL_LOG_LEVEL_DBG=n
